menu:
  home: /
  archive: /archives
  about: /about
  rss: /atom.xml

banner: image/background.jpg
avatar: https://pbs.twimg.com/profile_images/605116406724706304/3zmRL_LG_400x400.jpg
favicon: https://pbs.twimg.com/profile_images/605116406724706304/3zmRL_LG_400x400.jpg
weixin: https://pbs.twimg.com/profile_images/605116406724706304/3zmRL_LG_400x400.jpg

social:
  github: http://github.com/kidposeidon

# Comment
# e.g uyan: 2128137
uyan: 2128137

# Analytics
# google-analytics:
ga: UA-92791318-1

# Copyright Infomation
startyear: 2018

# Support hexo-renderer-scss
node_sass:
  debug: false
  outputStyle: nested
  precision: 5
  sourceComments: false

# Resume related
resume:
